# Generated by Django 5.0.2 on 2024-02-10 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptionist',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='Duty_time',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.CreateModel(
            name='BookAppointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('token_no', models.CharField(max_length=10)),
                ('apnt_date', models.DateTimeField()),
                ('register_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmsapp.receptionist')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmsapp.staff')),
            ],
        ),
    ]
