# Generated by Django 5.0.2 on 2024-02-11 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0002_alter_receptionist_email_alter_staff_duty_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('diagnosis_id', models.AutoField(primary_key=True, serialize=False)),
                ('diagnosis', models.CharField(max_length=255)),
                ('notes', models.CharField(max_length=500)),
                ('med_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmsapp.medicine')),
                ('register_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmsapp.receptionist')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmsapp.labtest')),
            ],
        ),
    ]
