# Generated by Django 5.0.2 on 2024-02-11 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0003_diagnosis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtest',
            name='normal_range',
        ),
    ]
