# Generated by Django 5.0.2 on 2024-02-11 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0004_remove_labtest_normal_range'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='quantity',
        ),
    ]
