# Generated by Django 5.0.2 on 2024-02-11 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0006_remove_diagnosis_med_id_remove_diagnosis_test_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='Medicine_prefered',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='Take_test',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AddField(
            model_name='medicine',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='notes',
            field=models.CharField(default=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='exp_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 11, 12, 9, 25, 573505, tzinfo=datetime.timezone.utc)),
        ),
    ]
