# Generated by Django 5.0.2 on 2024-02-12 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0007_diagnosis_medicine_prefered_diagnosis_take_test_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='Medicine_prefered',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='Take_test',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='notes',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='exp_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 12, 7, 22, 31, 316435, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='receptionist',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
