# Generated by Django 5.0.2 on 2024-02-12 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0009_alter_bookappointment_apnt_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='exp_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 12, 7, 34, 33, 175018, tzinfo=datetime.timezone.utc)),
        ),
    ]
