# Generated by Django 5.0.2 on 2024-02-13 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0010_alter_medicine_exp_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='medicine',
            name='exp_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 13, 12, 57, 50, 188081, tzinfo=datetime.timezone.utc)),
        ),
    ]
