# Generated by Django 5.0 on 2024-01-08 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ottapp', '0003_profilenew'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profilenew',
        ),
    ]
