# Generated by Django 5.0 on 2024-01-11 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ottapp', '0006_rating_recentlyviewed_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('url', models.URLField()),
                ('poster', models.ImageField(blank=True, null=True, upload_to='movie_posters/')),
                ('language', models.CharField(max_length=50)),
                ('cast', models.ManyToManyField(to='ottapp.actor')),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ottapp.director')),
                ('genres', models.ManyToManyField(to='ottapp.genre')),
            ],
        ),
        migrations.CreateModel(
            name='ChildMovieNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('url', models.URLField()),
                ('poster', models.ImageField(blank=True, null=True, upload_to='movie_posters/')),
                ('language', models.CharField(max_length=50)),
                ('director_name', models.CharField(max_length=255)),
                ('cast', models.ManyToManyField(blank=True, related_name='cast_relations', to='ottapp.childmovienew')),
                ('genres', models.ManyToManyField(blank=True, related_name='genre_relations', to='ottapp.childmovienew')),
            ],
        ),
    ]
