# Generated by Django 5.0 on 2024-01-11 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ottapp', '0007_childmovie_childmovienew'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChildMovie',
        ),
    ]
