# Generated by Django 5.0 on 2024-01-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ottapp', '0008_delete_childmovie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childmovienew',
            name='cast',
        ),
        migrations.RemoveField(
            model_name='childmovienew',
            name='genres',
        ),
        migrations.AddField(
            model_name='childmovienew',
            name='cast',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='childmovienew',
            name='genres',
            field=models.CharField(default='', max_length=500),
        ),
    ]
